Improve tar compilation
Fixes:
```
  CC       system.o
  CC       tar.o
tar.c:1351:5: error: 'SAVEDIR_SORT_INODE' undeclared here (not in a function)
     SAVEDIR_SORT_INODE
     ^
```

Caused by: 
https://github.com/Distrotech/tar/blob/273975bec1ff7d591d7ab8a63c08a02a285ffad3/m4/d-ino.m4#L21-L38